// import Link from 'next/link';
import React from 'react';

import { fetchAPI } from '../../lib/fetch-client';
import { getMenu } from '../../lib/query/pages.data';
import Nav from '../components/Nav';

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { menuItems } = await fetchAPI(getMenu, { id: 'PRIMARY' }, true);

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Nav menuItems={menuItems} />
        {/* <ul>
          <li><Link href="/">Home</Link></li>
          <li><Link href="/about">About</Link></li>
        </ul> */}
        {children}
      </body>
    </html>
  );
}
