// @ts-nocheck
import { ReactNode } from 'react';

import Nav from './components/Nav';

export default async function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Nav />
        {children}
      </body>
    </html>
  );
}
