import React from 'react';

import { fetchAPI } from '../lib/fetch-client';
import { getMenu } from '../lib/query/pages.data';
import Nav from '../src/components/Nav';
import RootStyleRegistry from './RootStyleRegistry';

import '../src/styles/reset.css';

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const { menuItems: { nodes: menuItems } } = await fetchAPI(getMenu, { id: 'PRIMARY' }, true);

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <RootStyleRegistry>
          <main>
            <Nav menuItems={menuItems} />
            {children}
          </main>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
